#!/usr/bin/env python3

import os, re

def in_cwd(file: str) -> bool:
    r = re.search("\/.*\/", file)  # if it has two /, its not in cwd
    if r:
        return False
    return True

def solved(file: str) -> bool:
    read_file = ""
    with open(file, "r") as f:
        read_file = f.read()
    
    r = re.search("Solved!", read_file)
    if r:
        return True
    return False

if __name__ == "__main__":
    # look in ./<difficulty>/<problem_name>/README.md
    # does the readme contain "Solved!".
    # if not, add it to the list of unfinished to print.

    files = [os.path.join(root, name)
             for root, dirs, files in os.walk("./")  # look in subfolders
             for name in files
             if name == "README.md"]  # if its the readme, we want it

    print("Unsolved files:")
    for file in files:
        if not in_cwd(file):  # ignore readmes in the main folder
            if not solved(file):
                print(file)

